apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scalable-pod-identifier-sm
  namespace: metrics
  labels:
    serviceMonitorSelector: prometheus
spec:
  endpoints:
  - port: '8080'
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: scaletestapp
